---
Name: sitebanner
---
NZTA\SiteBanner\Models\SiteBanner:
  extensions:
    - NZTA\SiteBanner\Extensions\PageSelectionExtension

NZTA\SiteBanner\Extensions\PageSelectionExtension:
  enabled: false

# SilverStripe\SiteConfig\SiteConfig:
#   extensions:
#     - NZTA\SiteBanner\Extensions\SiteConfigExtension
# NZTA\SiteBanner\Models\SiteBanner:
#   required_permission_codes:
#     - ADMIN
#   banner_types: [identifier: title]
#   embargo_enabled: true
